In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc

In [2]:
df = pd.read_csv('C:/부동산/data/finaldata_전처리.csv')

In [3]:
a = input()
df_region = df[df['구'] == a]
print(a)

은평구


In [4]:
df_region.columns

Index(['계약년월일', '전용면적', '거래금액', '층', '건축년도', '면적당가격', '구', '동', '계약년', '계약월',
       '계약일', '년월', '일자', '주택담보대출', '미국달러', '일본엔', '유로', '소비자물가지수',
       '소비자물가지수증감률', 'KOSPI_종가', 'KOSDAQ_종가', '무담보콜금리', 'KORIBOR', 'CD',
       '국고채_1년', '국고채_10년'],
      dtype='object')

In [5]:
X = df_region[['전용면적', '층', '건축년도', '계약년', '계약월',
       '주택담보대출', '미국달러', '일본엔', '유로',
       'KOSPI_종가', 'KOSDAQ_종가', '무담보콜금리', 'KORIBOR', 'CD',
       '국고채_1년', '국고채_10년']]
y = df_region['면적당가격']

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
model = LinearRegression().fit(X_train, y_train)

print("학습용 : ", model.score(X_train, y_train))
print("검증용 : ", model.score(X_test, y_test))

학습용 :  0.6832074226280755
검증용 :  0.6779107541021047


In [7]:
predict = model.predict([[85.5, 9, 2020, 2020, 5, 4.58, 1228.7, 9.4222, 1332.83, 2425.08, 740.49, 3.269, 3.74, 3.8, 3.584, 3.411]])
predict

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1014.67670688])

In [8]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
model = DecisionTreeRegressor().fit(X_train, y_train)

print("학습용 : ", model.score(X_train, y_train))
print("검증용 : ", model.score(X_test, y_test))

학습용 :  0.9977220896302665
검증용 :  0.8695583894382163


In [9]:
predict = model.predict([[85.5, 9, 2020, 2020, 5, 4.58, 1228.7, 9.4222, 1332.83, 2425.08, 740.49, 3.269, 3.74, 3.8, 3.584, 3.411]])
predict

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([1188.65481935])

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)
model = RandomForestRegressor(n_jobs = -1).fit(X_train, y_train)

print("학습용 : ", model.score(X_train, y_train))
print("검증용 : ", model.score(X_test, y_test))

학습용 :  0.9882427891343714
검증용 :  0.9233282417016322


In [11]:
predict = model.predict([[85.5, 9, 2020, 2020, 5, 4.58, 1228.7, 9.4222, 1332.83, 2425.08, 740.49, 3.269, 3.74, 3.8, 3.584, 3.411]])
predict

c:\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([1241.59035665])

In [15]:
df_region[df_region['년월'] == 202301]['면적당가격'].mean()

989.9590754464554